# kustomize config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml 
  - security/secret-provider.yaml
  - cert-manager.yaml
  - namespace.yaml
  - gateway.yaml
  - hpa.yaml
  - otel-collector.yaml


