apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: todo-sa
      containers:
        - name: backend
          image: backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for secrets..."

              while [ ! -f /mnt/secrets/db-user ] || \
                    [ ! -f /mnt/secrets/db-password ] || \
                    [ ! -f /mnt/secrets/db-host ] || \
                    [ ! -f /mnt/secrets/db-name ] || \
                    [ ! -f /mnt/secrets/secret-key ]; do
                sleep 2
              done

              echo "Secrets ready!"

              export DB_USER=$(cat /mnt/secrets/db-user)
              export DB_PASSWORD=$(cat /mnt/secrets/db-password)
              export DB_HOST=$(cat /mnt/secrets/db-host)
              export DB_NAME=$(cat /mnt/secrets/db-name)
              export SECRET_KEY=$(cat /mnt/secrets/secret-key)

              echo "Starting Django backend..."

              exec gunicorn config.wsgi:application \
                --bind 0.0.0.0:8000 \
                --workers 3
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          startupProbe:
            httpGet:
              path: /healthz/
              port: 8000
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz/
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readiness/
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-keyvault







