# Service Account with Azure Workload Identity
apiVersion: v1
kind: ServiceAccount
metadata:
  name: todo-sa
  namespace: todo-app
  annotations:
    azure.workload.identity/client-id: $USER_ASSIGNED_CLIENT_ID
  labels:
    azure.workload.identity/use: "true"
---


apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
  namespace: todo-app
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: ${USER_ASSIGNED_CLIENT_ID}
    keyvaultName: ${KEYVAULT_NAME}
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: db-user
          objectType: secret
          objectVersion: ""
        - |
          objectName: db-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: db-host
          objectType: secret
          objectVersion: ""
        - |
          objectName: db-name
          objectType: secret
          objectVersion: ""
        - |
          objectName: secret-key
          objectType: secret
          objectVersion: ""
    tenantId: ${TENANT_ID}